"""endpoint not requested now

Revision ID: 463c84f92b18
Revises: 377fab71fcfe
Create Date: 2025-12-19 03:53:38.835539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463c84f92b18'
down_revision: Union[str, Sequence[str], None] = '377fab71fcfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vcregistry', 'endpoint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vcregistry', 'endpoint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
