"""init

Revision ID: ef1ae3951895
Revises: 
Create Date: 2025-12-19 03:21:24.521612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ef1ae3951895'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ackey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_key_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('private_key_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vcregistry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_key_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('ac_signature_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vcregistry_name'), 'vcregistry', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vcregistry_name'), table_name='vcregistry')
    op.drop_table('vcregistry')
    op.drop_table('ackey')
    # ### end Alembic commands ###
