.TH "PROOFD FORMAT" "1" "2026-01-18" "0.1.0" "proofd format Manual"
.SH NAME
proofd\-format \- Format operations
.SH SYNOPSIS
.B proofd format
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Format operations
.SH COMMANDS
.PP
\fBinfo\fP
  .PP
  See \fBproofd format-info(1)\fP for full documentation on the \fBinfo\fP command.
.PP
\fBupgrade\fP
  .PP
  See \fBproofd format-upgrade(1)\fP for full documentation on the \fBupgrade\fP command.
