.TH "PROOFD CREATE" "1" "2026-01-18" "0.1.0" "proofd create Manual"
.SH NAME
proofd\-create \- Create .verify file for document
.SH SYNOPSIS
.B proofd create
[OPTIONS] FILE
.SH DESCRIPTION
Create .verify file for document
.SH OPTIONS
.TP
\fB\-a,\fP \-\-alg TEXT
[default: sha256]
.TP
\fB\-o,\fP \-\-out PATH
.PP
.TP
\fB\-f,\fP \-\-force
.PP
.TP
\fB\-V,\fP \-\-verifier TEXT
Add verifier ID (can be used multiple times)
