.TH "PROOFD VERIFIER" "1" "2026-01-18" "0.1.0" "proofd verifier Manual"
.SH NAME
proofd\-verifier \- Manage verifiers
.SH SYNOPSIS
.B proofd verifier
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage verifiers
.SH COMMANDS
.PP
\fBadd\fP
  .PP
  See \fBproofd verifier-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBremove\fP
  .PP
  See \fBproofd verifier-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBlist\fP
  .PP
  See \fBproofd verifier-list(1)\fP for full documentation on the \fBlist\fP command.
