.TH "PROOFD VERIFY" "1" "2026-01-18" "0.1.0" "proofd verify Manual"
.SH NAME
proofd\-verify \- Verify document using AC-resolved...
.SH SYNOPSIS
.B proofd verify
[OPTIONS] DOCUMENT VERIFY_FILE
.SH DESCRIPTION
.PP
Verify document using AC-resolved Verification Centers
.PP
.SH OPTIONS
.TP
\fB\-\-ac\fP TEXT
Authority Center base URL
.TP
\fB\-\-timeout\-ac\fP TEXT
.PP
.TP
\fB\-\-timeout\-vc\fP TEXT
.PP
.TP
\fB\-\-ignore\-ac\-public\fP
.PP
.TP
\fB\-\-ac\-public\-key\-b64\fP TEXT
.PP
