"""init

Revision ID: 401cd74ecb62
Revises: 
Create Date: 2025-12-19 01:22:52.103820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '401cd74ecb62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash_algo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_confirmations_document_hash'), 'document_confirmations', ['document_hash'], unique=True)
    op.create_table('vc_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_key_pem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('private_key_pem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vc_keys_active'), 'vc_keys', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vc_keys_active'), table_name='vc_keys')
    op.drop_table('vc_keys')
    op.drop_index(op.f('ix_document_confirmations_document_hash'), table_name='document_confirmations')
    op.drop_table('document_confirmations')
    # ### end Alembic commands ###
