"""added revocation fields

Revision ID: 46871c3fe0c7
Revises: 7ba32823114b
Create Date: 2025-12-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46871c3fe0c7'
down_revision: Union[str, Sequence[str], None] = '7ba32823114b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_confirmations', sa.Column('revoked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('document_confirmations', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_document_confirmations_revoked'), 'document_confirmations', ['revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_confirmations_revoked'), table_name='document_confirmations')
    op.drop_column('document_confirmations', 'revoked_at')
    op.drop_column('document_confirmations', 'revoked')
    # ### end Alembic commands ###