"""added confirmed at

Revision ID: 7ba32823114b
Revises: 401cd74ecb62
Create Date: 2025-12-19 01:29:39.837070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba32823114b'
down_revision: Union[str, Sequence[str], None] = '401cd74ecb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_confirmations', sa.Column('confirmed_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_confirmations', 'confirmed_at')
    # ### end Alembic commands ###
